# Change these first
owner: acecentre # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: gavinhenderson

sites:
  - name: Main Site
    url: http://acecentre.org.uk/
    favicon: https://acecentre.org.uk/favicon.ico
    assignees:
      - gavinhenderson
  - name: Backend
    url: https://backend.acecentre.org.uk/
    favicon: https://backend.acecentre.org.uk/favicon.ico
    assignees:
      - gavinhenderson
  - name: Moodle
    url: https://learning.acecentre.org.uk/
    favicon: https://learning.acecentre.org.uk/theme/image.php/super/theme/1650864752/favicon
    assignees:
      - gavinhenderson
  - name: Central
    url: https://central.acecentre.org.uk/
    favicon: https://central.acecentre.org.uk/favicon.ico
    assignees:
      - gavinhenderson

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://acecentre.org.uk/nav-logo.png
  name: Ace Centre
  introTitle: "Status"
  introMessage: This site tracks the status of Ace Centre websites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
